/*
 *
 * ListNewsEvent constants
 *
 */

export const DEFAULT_ACTION = 'app/ListNewsEvent/DEFAULT_ACTION';
export const GET_LIST_NEWS_ACTION = 'app/ListNewsEvent/GET_LIST_NEWS_ACTION';
export const GET_LIST_NEWS_ACTION_SUCCESS = 'app/ListNewsEvent/GET_LIST_NEWS_ACTION_SUCCESS';
export const GET_LIST_NEWS_ACTION_FAIL = 'app/ListNewsEvent/GET_LIST_NEWS_ACTION_FAIL';
export const DELETE_NEWS_ACTION = 'app/ListNewsEvent/DELETE_NEWS_ACTION';
export const DELETE_NEWS_ACTION_SUCCESS = 'app/ListNewsEvent/DELETE_NEWS_ACTION_SUCCESS';
export const DELETE_NEWS_ACTION_FAIL = 'app/ListNewsEvent/DELETE_NEWS_ACTION_FAIL';
export const ADD_NEWS_ACTION = 'app/ListNewsEvent/ADD_NEWS_ACTION';
export const ADD_NEWS_ACTION_SUCCESS = 'app/ListNewsEvent/ADD_NEWS_ACTION_SUCCESS';
export const ADD_NEWS_NOT_DATA_ACTION_SUCCESS = "app/ListNewsEvent/ADD_NEWS_NOT_DATA_ACTION_SUCCESS";
export const ADD_NEWS_NOT_DATA_ACTION_FAIL = "app/ListNewsEvent/ADD_NEWS_NOT_DATA_ACTION_FAIL";
export const GET_LIST_CATE_ACTION = 'app/ListNewsEvent/GET_LIST_CATE_ACTION';
export const GET_LIST_CATE_ACTION_SUCCESS = 'app/ListNewsEvent/GET_LIST_CATE_ACTION_SUCCESS';
export const ADD_TAGS_ACTION = 'app/ListNewsEvent/ADD_TAGS_ACTION';
export const ADD_TAGS_ACTION_SUCCESS = 'app/ListNewsEvent/ADD_TAGS_ACTION_SUCCESS';
export const ADD_TAGS_ACTION_FAIL = 'app/ListNewsEvent/ADD_TAGS_ACTION_FAIL';
export const UPDATE_IMAGE_NEWS_EVENT_ACTION = 'app/ListNewsEvent/UPDATE_IMAGE_NEWS_EVENT_ACTION';
export const UPDATE_IMAGE_NEWS_EVENT_ACTION_SUCCESS = 'app/ListNewsEvent/UPDATE_IMAGE_NEWS_EVENT_ACTION_SUCCESS';
export const UPDATE_IMAGE_NEWS_EVENT_ACTION_FAIL = 'app/ListNewsEvent/UPDATE_IMAGE_NEWS_EVENT_ACTION_FAIL';
export const UPDATE_NEWS_EVENT_ACTION = 'app/ListNewsEvent/UPDATE_NEWS_EVENT_ACTION';
export const UPDATE_NEWS_EVENT_ACTION_SUCCESS = 'app/ListNewsEvent/UPDATE_NEWS_EVENT_ACTION_SUCCESS';
export const UPDATE_NEWS_EVENT_ACTION_NO_DATA_SUCCESS = 'app/ListNewsEvent/UPDATE_NEWS_EVENT_ACTION_NO_DATA_SUCCESS';
export const UPDATE_NEWS_EVENT_ACTION_FAIL = 'app/ListNewsEvent/UPDATE_NEWS_EVENT_ACTION_FAIL';
export const GET_COMMENT_NEWS_EVENT_ACTION = 'app/ListNewsEvent/GET_COMMENT_NEWS_EVENT_ACTION';
export const GET_COMMENT_NEWS_EVENT_ACTION_SUCCESS = 'app/ListNewsEvent/GET_COMMENT_NEWS_EVENT_ACTION_SUCCESS';
export const GET_COMMENT_NEWS_EVENT_ACTION_FAIL = 'app/ListNewsEvent/GET_COMMENT_NEWS_EVENT_ACTION_FAIL';
export const INIT_PAGE_TOTAL_NEWS_EVENT_ACTION = 'app/ListNewsEvent/INIT_PAGE_TOTAL_NEWS_EVENT_ACTION';
export const DEL_COMMENT_NEWS_EVENT_ACTION = 'app/ListNewsEvent/DEL_COMMENT_NEWS_EVENT_ACTION';
export const DEL_COMMENT_NEWS_EVENT_ACTION_SUCCESS = 'app/ListNewsEvent/DEL_COMMENT_NEWS_EVENT_ACTION_SUCCESS';
export const DEL_COMMENT_NEWS_EVENT_ACTION_FAIL = 'app/ListNewsEvent/DEL_COMMENT_NEWS_EVENT_ACTION_FAIL';

