
export const DEFAULT_ACTION = 'app/InFoListExpert/DEFAULT_ACTION';
export const GET_LIST_EXPERT_ACTION = 'app/InFoListExpert/GET_LIST_EXPERT_ACTION';
export const GET_LIST_EXPERT_ACTION_SUCCESS = 'app/InFoListExpert/GET_LIST_EXPERT_ACTION_SUCCESS';
export const GET_LIST_EXPERT_ACTION_ERROR = 'app/InFoListExpert/GET_LIST_EXPERT_ACTION_ERROR';
export const ADD_EXPERT_ACTION = 'app/InFoListExpert/ADD_EXPERT_ACTION';
export const ADD_EXPERT_ACTION_SUCCESS = 'app/InFoListExpert/ADD_EXPERT_ACTION_SUCCESS';
export const ADD_EXPERT_ACTION_NO_DATA_SUCCESS = 'app/InFoListExpert/ADD_EXPERT_ACTION_NO_DATA_SUCCESS';
export const ADD_EXPERT_ACTION_ERROR = 'app/InFoListExpert/ADD_EXPERT_ACTION_ERROR';
