
export const DEFAULT_ACTION = 'app/ExpertDetail/DEFAULT_ACTION';
export const GET_EXPERT_DETAIL_ACTION = 'app/ExpertDetail/GET_EXPERT_DETAIL_ACTION';
export const GET_EXPERT_DETAIL_ACTION_SUCCESS = 'app/ExpertDetail/GET_EXPERT_DETAIL_ACTION_SUCCESS';
export const GET_EXPERT_DETAIL_ACTION_ERROR = 'app/ExpertDetail/GET_EXPERT_DETAIL_ACTION_ERROR';
export const GET_LIST_FIELD_ACTION = 'app/ExpertDetail/GET_LIST_FIELD_ACTION';
export const GET_LIST_FIELD_ACTION_SUCCESS = 'app/ExpertDetail/GET_LIST_FIELD_ACTION_SUCCESS';
export const UPDATE_DEGREE_ACTION = 'app/ExpertDetail/UPDATE_DEGREE_ACTION';
export const UPDATE_DEGREE_ACTION_SUCCESS = 'app/ExpertDetail/UPDATE_DEGREE_ACTION_SUCCESS';
export const UPDATE_DEGREE_ACTION_ERROR = 'app/ExpertDetail/UPDATE_DEGREE_ACTION_ERROR';
export const GET_LIST_SUB_FIELD_ACTION = 'app/ExpertDetail/GET_LIST_SUB_FIELD_ACTION';
export const GET_LIST_SUB_FIELD_ACTION_SUCCESS = 'app/ExpertDetail/GET_LIST_SUB_FIELD_ACTION_SUCCESS';
export const UPDATE_SUB_FIELD_ACTION = 'app/ExpertDetail/UPDATE_SUB_FIELD_ACTION';
export const UPDATE_SUB_FIELD_ACTION_SUCCESS = 'app/ExpertDetail/UPDATE_SUB_FIELD_ACTION_SUCCESS';
export const UPDATE_SUB_FIELD_ACTION_ERROR = 'app/ExpertDetail/UPDATE_SUB_FIELD_ACTION_ERROR';
export const UPDATE_TAGS_ACTION = 'app/ExpertDetail/UPDATE_TAGS_ACTION';
export const UPDATE_TAGS_ACTION_SUCCESS = 'app/ExpertDetail/UPDATE_TAGS_ACTION_SUCCESS';
export const UPDATE_TAGS_ACTION_ERROR = 'app/ExpertDetail/UPDATE_TAGS_ACTION_ERROR';
